input {
    kb_layout = latam
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

cursor {
    hotspot_padding = 1
}

device {
    name = hs-g61
    kb_layout = us
    kb_variant = altgr-intl
}
